// SignIn, Forgetpassword and Signup pages icons
export { default as LoginImage } from '../assets/img/login.jpg'
export { default as Logo } from '../assets/img/logo.png'
export { default as LogoWhite } from '../assets/img/logo-white.png'
export { default as MailIcon } from '../assets/img/icons/mail.svg'
export { default as GoogleIcon } from '../assets/img/icons/google.png'
export { default as FacebookIcon } from '../assets/img/icons/facebook.png'
export { default as Users1 } from '../assets/img/icons/users1.svg'

//Dashboard icons

export { default as Dash1 } from '../assets/img/icons/dash1.svg'
export { default as Dash2 } from '../assets/img/icons/dash2.svg'
export { default as Dash3 } from '../assets/img/icons/dash3.svg'
export { default as Dash4 } from '../assets/img/icons/dash4.svg'
export {default as Dropdown} from '../assets/img/icons/dropdown.svg'
export { default as Product1 } from '../assets/img/product/product1.jpg'
export { default as Product7 } from '../assets/img/product/product7.jpg'
export { default as Product8 } from '../assets/img/product/product8.jpg'
export { default as Product9 } from '../assets/img/product/product9.jpg'
export { default as EarpodIcon } from '../assets/img/product/product22.jpg'
export { default as Product12 } from '../assets/img/product/product12.jpg'
export { default as Product13 } from '../assets/img/product/product13.jpg'
export { default as Product15 } from '../assets/img/product/product15.jpg'
export {default as IphoneIcon} from '../assets/img/product/product23.jpg'
export {default as SamsungIcon} from '../assets/img/product/product24.jpg'
export {default as MacbookIcon} from '../assets/img/product/product6.jpg'
export {default as OrangeImage} from '../assets/img/product/product2.jpg'
export {default as PineappleImage} from '../assets/img/product/product3.jpg'
export {default as StawberryImage} from '../assets/img/product/product4.jpg'
export {default as AvocatImage} from '../assets/img/product/product5.jpg'
export {default as PlusIcon} from '../assets/img/icons/plus.svg'
export {default as ClosesIcon} from '../assets/img/icons/closes.svg'
export {default as Pdf} from '../assets/img/icons/pdf.svg'
export {default as Excel} from '../assets/img/icons/excel.svg'
export {default as Printer} from '../assets/img/icons/printer.svg'
export {default as Search} from '../assets/img/icons/search-white.svg'
export {default as Filter} from '../assets/img/icons/filter.svg'
export {default as Upload} from '../assets/img/icons/upload.svg'
export {default as EyeIcon} from '../assets/img/icons/eye.svg'
export {default as EditIcon} from '../assets/img/icons/edit.svg'
export {default as DeleteIcon} from '../assets/img/icons/delete.svg'
export {default as Dashboard} from '../assets/img/icons/dashboard.svg'
export {default as Noimage} from '../assets/img/product/noimage.png'


//header
export {default as SmallLogo} from '../assets/img/logo-small.png'
export {default as Closes} from '../assets/img/icons/closes.svg'
export {default as HeaderSearch} from '../assets/img/icons/search.svg'
export {default as Flag} from '../assets/img/flags/us1.png'

export {default as FlagUS} from '../assets/img/flags/us.png'
export {default as FlagFR} from '../assets/img/flags/fr.png'
export {default as FlagES} from '../assets/img/flags/es.png'
export {default as FlagDE} from '../assets/img/flags/de.png'
export {default as Notification} from '../assets/img/icons/notification-bing.svg'
export {default as Avatar2} from '../assets/img/profiles/avatar-02.jpg'
export {default as Avatar3} from '../assets/img/profiles/avatar-03.jpg'
export {default as Avatar6} from '../assets/img/profiles/avatar-06.jpg'
export {default as Avatar17} from '../assets/img/profiles/avatar-17.jpg'
export {default as Avatar13} from '../assets/img/profiles/avatar-13.jpg'
export {default as Avatar} from '../assets/img/profiles/avator1.jpg'
export {default as Avatar1} from '../assets/img/profiles/avator1.jpg'
export {default as Logout} from '../assets/img/icons/log-out.svg'

export {default as Customer5} from '../assets/img/customer/customer5.jpg'
export {default as Customer6} from '../assets/img/customer/customer6.jpg'
export {default as Customer7} from '../assets/img/customer/customer7.jpg'
export {default as Customer8} from '../assets/img/customer/customer8.jpg'
export {default as EditSet} from '../assets/img/icons/edit-set.svg'
export {default as Macbook} from '../assets/img/icons/macbook.svg'
export {default as Samsung} from '../assets/img/brand/samsung.png'

export {default as Scanner} from '../assets/img/icons/scanners.svg'
export {default as scanner1} from '../assets/img/icons/scanner1.svg'
export {default as Plus} from '../assets/img/icons/plus1.svg'
export {default as MinusIcon} from '../assets/img/icons/minus.svg'

export {default as Product} from '../assets/img/icons/product.svg'
export {default as Purchase} from '../assets/img/icons/purchase1.svg'
export{default as Calendar} from '../assets/img/icons/calendars.svg'
export{default as Expense} from '../assets/img/icons/expense1.svg'
export{ default as Dollar} from '../assets/img/icons/dollar.svg'
export{ default as UnpaidGray} from '../assets/img/product/product10.jpg'
export{ default as Quotation} from '../assets/img/icons/quotation1.svg'
export {default as Transfer} from '../assets/img/icons/transfer1.svg'
export {default as Return } from '../assets/img/icons/return1.svg'
export {default as People} from'../assets/img/icons/users1.svg'
export {default as Thomas} from '../assets/img/customer/customer1.jpg'
export {default as Benjamin} from '../assets/img/customer/customer2.jpg'
export {default as James} from '../assets/img/customer/customer3.jpg'
export {default as Bruklin} from '../assets/img/customer/customer4.jpg'
export {default as Beverly} from '../assets/img/customer/customer5.jpg'
export {default as Profile2} from '../assets/img/customer/profile2.jpg'
export{ default as Places} from '../assets/img/icons/places.svg'
export {default as Avatar02} from '../assets/img/profiles/avatar-02.jpg'
export {default as Avatar03} from '../assets/img/profiles/avatar-03.jpg'
export {default as Avatar04} from '../assets/img/profiles/avatar-04.jpg'
export {default as CardImage} from '../assets/img/img-01.jpg'
export {default as Time} from '../assets/img/icons/time.svg'
export {default as settings} from '../assets/img/icons/settings.svg'
export {default as search_whites} from '../assets/img/icons/search-whites.svg'
export {default as barcode1} from '../assets/img/barcode1.png'


export {default as Profile3} from '../assets/img/customer/profile3.jpg'
export {default as Profile4} from '../assets/img/customer/profile4.jpg'
export {default as Profile5} from '../assets/img/customer/profile5.jpg'

export {default as Sales1} from '../assets/img/icons/sales1.svg'
export {default as cash} from '../assets/img/icons/cash.svg'
export {default as Eye1} from '../assets/img/icons/eye1.svg'
export {default as Dollar1} from '../assets/img/icons/dollar-square.svg'
export {default as plusCircle} from '../assets/img/icons/plus-circle.svg'
export {default as Download} from '../assets/img/icons/download.svg'
export {default as Edit5} from '../assets/img/icons/edit-5.svg'
export {default as delete1} from '../assets/img/icons/delete1.svg'
export {default as delete2} from '../assets/img/icons/delete-2.svg'
export {default as ellipise1} from '../assets/img/icons/ellipise1.svg'
export {default as datepicker} from '../assets/img/icons/datepicker.svg'
export {default as debitcard} from '../assets/img/icons/debitcard.svg'
export {default as scan} from '../assets/img/icons/scan.svg'
export {default as pause1} from '../assets/img/icons/pause1.svg'
export {default as Edit6} from '../assets/img/icons/edit-6.svg'
export {default as trash12} from '../assets/img/icons/trash12.svg'
export {default as wallet1} from '../assets/img/icons/wallet1.svg'
export {default as transcation} from '../assets/img/icons/transcation.svg'
export {default as Closecircle} from '../assets/img/icons/close-circle.svg'
export {default as Closecircle1} from '../assets/img/icons/close-circle1.svg'
export {default as reverse} from '../assets/img/icons/reverse.svg'
export {default as Adidas} from '../assets/img/brand/adidas.png'
export {default as Colgate} from '../assets/img/brand/colgate.png'

export { default as Product61 } from '../assets/img/product/product61.png'
export { default as Product62 } from '../assets/img/product/product62.png'
export { default as Product63 } from '../assets/img/product/product63.png'
export { default as Product64 } from '../assets/img/product/product64.png'
export { default as Product65 } from '../assets/img/product/product65.png'
export { default as Product66 } from '../assets/img/product/product66.png'
export { default as Product67 } from '../assets/img/product/product67.png'
export { default as Product68 } from '../assets/img/product/product68.png'
export { default as Product69 } from '../assets/img/product/product69.jpg'

export { default as Product29 } from '../assets/img/product/product29.jpg'
export { default as Product30 } from '../assets/img/product/product30.jpg'
export { default as Product31 } from '../assets/img/product/product31.jpg'
export { default as Product34 } from '../assets/img/product/product34.jpg'
export { default as Product35 } from '../assets/img/product/product35.jpg'
export { default as Product37 } from '../assets/img/product/product37.jpg'
export { default as Product54 } from '../assets/img/product/product54.jpg'
export { default as Product44 } from '../assets/img/product/product44.jpg'
export { default as Product45 } from '../assets/img/product/product45.jpg'
export { default as Product36 } from '../assets/img/product/product36.jpg'
export { default as Product32 } from '../assets/img/product/product32.jpg'
export { default as Product46 } from '../assets/img/product/product46.jpg'
export { default as Product55 } from '../assets/img/product/product55.jpg'
export { default as Product60 } from '../assets/img/product/product60.jpg'
export { default as Product56 } from '../assets/img/product/product56.jpg'
export { default as Product47 } from '../assets/img/product/product47.jpg'
export { default as Product48 } from '../assets/img/product/product48.png'
export { default as Product57 } from '../assets/img/product/product57.jpg'
export { default as Product58 } from '../assets/img/product/product58.jpg'
export { default as Product49 } from '../assets/img/product/product49.jpg'
export { default as Product51 } from '../assets/img/product/product51.jpg'
export { default as Product52 } from '../assets/img/product/product52.jpg'
export { default as Product53 } from '../assets/img/product/product53.jpg'


export { default as sidebar_icon_01 } from '../assets/img/icons/sidebar-icon-01.svg'
export { default as sidebar_icon_02 } from '../assets/img/icons/sidebar-icon-02.svg'
export { default as sidebar_icon_03 } from '../assets/img/icons/sidebar-icon-03.svg'
export { default as sun_icon } from '../assets/img/icons/sun-icon.svg'
export { default as layout_ltr } from '../assets/img/layout-ltr.png'
export { default as layout_rtl } from '../assets/img/layout-rtl.png'
export { default as layout_04 } from '../assets/img/layout-04.png'
export { default as layout_01 } from '../assets/img/layout-01.png'

export { default as close_icon } from '../assets/img/icons/close-icon.svg'
export { default as menu_icon } from '../assets/img/icons/menu-icon.svg'
export { default as menu_icon01} from '../assets/img/icons/menu-icon-01.svg'
export { default as menu_icon02} from '../assets/img/icons/menu-icon-02.svg'
export { default as menu_icon04} from '../assets/img/icons/menu-icon-04.svg'
export { default as menu_icon05} from '../assets/img/icons/menu-icon-05.svg'
export { default as menu_icon06} from '../assets/img/icons/menu-icon-06.svg'
export { default as layout_03} from '../assets/img/layout-03.png'